Update java-project-ci.yml

diff --git a/.github/workflows/java-project-ci.yml b/.github/workflows/java-project-ci.yml
--- a/.github/workflows/java-project-ci.yml
+++ b/.github/workflows/java-project-ci.yml
@@ -104,9 +104,9 @@ jobs:
         id: compilation
         run: |
           echo "Set the project artifacts version"
-          echo "mvn versions:set -DnewVersion=${{ env.RELEASE_NAME }} -B -DgenerateBackupPoms=true -DprocessAllModules=true"
+          echo "mvn versions:set -DnewVersion=$RELEASE_NAME -B -DgenerateBackupPoms=true -DprocessAllModules=true"
           echo "Execute the java project(s) build via Maven tool"
-          echo "mvn --batch-mode --update-snapshots --show-version --fail-fast --file pom.xml clean compile -Drevision=${{ env.RELEASE_NAME }}""
+          echo "mvn --batch-mode --update-snapshots --show-version --fail-fast --file pom.xml clean compile -Drevision=$RELEASE_NAME"
           echo "RELEASE_NAME=$RELEASE_NAME" >> $GITHUB_OUTPUT
         env:
             MAVEN_USERNAME: ${{ secrets.SPACE_CYBNITY_OS_REPO_USERNAME }}
